Repository codeforpdx/codepdx_website, pull requests merged in 2023-10, with the labels that each got.

#14 skeleton of component structure
  src/App.jsx
  src/Layout.jsx
  src/components/global/Footer.jsx
  src/components/global/Navbar.jsx
  src/components/home/About.jsx
  src/components/home/Events.jsx
  src/components/home/Hero.jsx
  src/components/home/ProjectsBrief.jsx
  src/components/home/VolunteerBrief.jsx
  src/components/home/partners/CallToAction.jsx
  src/components/home/partners/Partners.jsx
  src/components/home/partners/PrimaryPartner.jsx
  src/components/home/partners/SecondaryPartner.jsx
  src/components/projects/ProjectBox.jsx
  src/components/volunteer/Steps.jsx
  src/pages/Home.jsx
  src/pages/Projects.jsx
  src/pages/Volunteer.jsx
Labels: enhancement

#15 change import to fix error
  src/pages/Home.jsx
Labels: bug

#16 Adding documentation and linting config
  .eslintignore
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .prettierignore
  .prettierrc.cjs
  README.md
  contributing.md
  package-lock.json
  package.json
  src/App.jsx
  src/main.jsx
  vite.config.js
Labels: documentation

#19 Issue 6/create volunteer section
  dist/assets/index-d526a0c5.css
  dist/assets/index-e92ae01e.js
  dist/assets/react-35ef61ed.svg
  dist/index.html
  package-lock.json
  package.json
  public/assets/logoBlob.svg
  public/assets/rose_logo.png
  public/assets/socialsBlob.svg
  src/Layout.jsx
  src/components/home/VolunteerBrief.jsx
  src/components/volunteer/Steps.jsx
  src/theme.js
Labels: enhancement

#25 Fix footer formatting issue
  src/components/global/Footer.jsx
Labels: bug

#27 creating 404 page
  public/assets/notfound.webp
  src/Layout.jsx
  src/pages/NoPageFound.jsx
Labels: enhancement

#23 3 create hero section of landing page
  public/assets/stJohnsBridge.png
  src/components/home/Hero.jsx
Labels: enhancement

#30 Added container to body
  src/Layout.jsx
  src/components/home/VolunteerBrief.jsx
  src/pages/Home.jsx
  src/pages/Projects.jsx
  src/pages/Volunteer.jsx
Labels: bug, enhancement
