Repository codeforpdx/codepdx_website, pull requests merged in 2023-11, with the labels that each got.

#39 Issue 34/create our projects brief
  index.html
  package-lock.json
  public/assets/PassLogo.png
  public/assets/logoRecordSponge.svg
  src/components/home/ProjectsBrief.jsx
  src/components/projects/projectsList.js
  src/pages/Projects.jsx
Labels: enhancement

#32 Issue 8/create our projects section
  package-lock.json
  src/components/projects/ProjectBox.jsx
  src/components/projects/projectsList.jsx
  src/pages/Projects.jsx
Labels: enhancement

#45 43 create volunteer page hero
  public/assets/projectsHeroImage.png
  public/assets/volunteerHeroImage.png
  src/components/global/Hero/Hero.jsx
  src/components/global/Hero/styles.js
  src/components/home/Hero.jsx
  src/pages/Home.jsx
  src/pages/Projects.jsx
  src/pages/Volunteer.jsx
Labels: enhancement, good first issue

#47 fix dependencies that were accidently removed, fix import statement f…
  package-lock.json
  src/pages/Projects.jsx
Labels: bug

#40 About
  src/components/home/About.jsx
Labels: enhancement

#50 Issue 7b/create volunteer page 2
  package-lock.json
  package.json
  src/components/home/Events.jsx
  src/components/volunteer/Steps.jsx
  src/components/volunteer/VolunteerSteps.jsx
  src/components/volunteer/volunteerStepsData.jsx
  src/pages/Volunteer.jsx
  vite.config.js
Labels: enhancement

#68 Enhance 404 page
  src/pages/NoPageFound.jsx
Labels: enhancement

#69 Issue 61/volunteer section enhancements
  src/components/home/VolunteerBrief.jsx
Labels: enhancement
